local format = require("goctl.format")

describe("goctl.format", function()
  describe("parse_error", function()
    it("parses standard error format", function()
      local result = format.parse_error("10:5 unexpected token")
      assert.is_not_nil(result)
      assert.equals(10, result.line)
      assert.equals(5, result.col)
      assert.equals("unexpected token", result.message)
    end)

    it("parses error with just line number", function()
      local result = format.parse_error("42: syntax error")
      assert.is_not_nil(result)
      assert.equals(42, result.line)
      assert.equals(0, result.col)
      assert.equals("syntax error", result.message)
    end)

    it("returns nil for unparseable errors", function()
      local result = format.parse_error("some random error message")
      assert.is_nil(result)
    end)

    it("handles complex error messages", function()
      local result = format.parse_error("15:20 expected '}' but got 'EOF'")
      assert.is_not_nil(result)
      assert.equals(15, result.line)
      assert.equals(20, result.col)
      assert.equals("expected '}' but got 'EOF'", result.message)
    end)
  end)

  describe("format", function()
    it("returns error for unnamed buffer", function()
      local buf = vim.api.nvim_create_buf(false, true)
      vim.api.nvim_set_current_buf(buf)

      local result = format.format()
      assert.is_false(result.success)
      assert.equals("unnamed buffer", result.error)

      vim.api.nvim_buf_delete(buf, { force = true })
    end)
  end)
end)
